# Generated by Django 2.0.3 on 2018-05-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env_name', models.CharField(max_length=32, verbose_name='环境名称')),
                ('base_url', models.CharField(max_length=120, verbose_name='环境URL')),
                ('explorer_name', models.CharField(max_length=32, verbose_name='浏览器名称')),
                ('explorer_version', models.CharField(max_length=32, verbose_name='浏览器版本')),
                ('simple_desc', models.CharField(max_length=120, null=True, verbose_name='简要描述')),
            ],
            options={
                'verbose_name': '测试环境信息',
                'db_table': 'EnvInfo',
            },
        ),
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module_name', models.CharField(max_length=64, verbose_name='模块名称')),
                ('test_user', models.CharField(max_length=120, verbose_name='测试人员')),
                ('simple_desc', models.CharField(max_length=120, verbose_name='简要描述')),
            ],
            options={
                'verbose_name': '模块信息',
                'db_table': 'ModuleInfo',
            },
        ),
        migrations.CreateModel(
            name='Projectinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('dev_leader', models.CharField(max_length=32, verbose_name='开发负责人')),
                ('test_leader', models.CharField(max_length=32, verbose_name='测试负责人')),
                ('simple_desc', models.CharField(max_length=120, null=True, verbose_name='简要描述')),
                ('other_desc', models.CharField(max_length=120, null=True, verbose_name='其他描述')),
            ],
            options={
                'verbose_name': '项目信息',
                'db_table': 'Projectinfo',
            },
        ),
        migrations.CreateModel(
            name='TestCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case_name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('case_desc', models.CharField(max_length=240, verbose_name='用例描述')),
                ('belong_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataServer.ModuleInfo')),
            ],
            options={
                'verbose_name': '测试用例信息',
                'db_table': 'TestCaseInfo',
            },
        ),
        migrations.CreateModel(
            name='TestCaseScriptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('script_name', models.CharField(max_length=200, verbose_name='脚本名称')),
                ('belong_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataServer.TestCaseInfo')),
            ],
            options={
                'verbose_name': '测试脚本信息',
                'db_table': 'TestCaseScriptInfo',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=12, verbose_name='用户名')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('status', models.IntegerField(default=1, verbose_name='可用/不可用')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
        migrations.AddField(
            model_name='moduleinfo',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataServer.Projectinfo'),
        ),
    ]
