# Generated by Django 2.0.3 on 2018-05-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180525_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinfo',
            name='other_desc',
            field=models.CharField(max_length=120, null=True, verbose_name='其他描述'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='case_desc',
            field=models.TextField(null=True, verbose_name='用例描述'),
        ),
    ]
