# Generated by Django 2.0.3 on 2018-05-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180524_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinfo',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ProjectInfo'),
        ),
    ]
